### ISSUE TITLE
MAJOR WRONG PATCH

### ISSUE THREAD

**Issue by iceraft** [iceraft/WAD_Project#14]
thx to org aku suh check tapi dia cakap xde pape

**Comment by iceraft** [comment]
aku dah revert sebelum patch update kat new branch ... kalau ko nk elok2kan ke apa ko buat kat tepi aku nk siapkan customer view ... screenshot x amik lagi x yah nak semangat sgt siapkan problem tu

**Comment by ashrafkamarudin** [comment]
weh aku dah try merge ko punye dgn erin punye tapi ade error masa nak insert participant. cube ko check kat repo aku branch erinx. kat ko ade problem tak.

**Comment by iceraft** [comment]
ada
